//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public int UserId { get; set; }
        public string BookId { get; set; }
        public int ActualRate { get; set; }
        public Nullable<int> PredictedRate { get; set; }
        public Nullable<double> Error { get; set; }
        public int ParametersSet { get; set; }
        public int Id { get; set; }
        public int CrossTestVariant { get; set; }
    
        public virtual Parameter Parameter { get; set; }
    }
}
