//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSimilar
    {
        public int UserId { get; set; }
        public int NeighborId { get; set; }
        public Nullable<double> Similarity { get; set; }
        public long Id { get; set; }
        public int ParametersSet { get; set; }
    
        public virtual Parameter Parameter { get; set; }
        public virtual User User { get; set; }
    }
}
